// Mock products as fallback
export const mockProducts = [
  {
    id: "1",
    name: "Urban Commuter Backpack",
    description:
      "A stylish and functional backpack for daily commuting. Features a padded laptop sleeve and multiple compartments.",
    price: 3500,
    category: "backpacks",
    image: "https://placehold.co/600x600?text=Backpack",
    stock: 10,
    rating: 4.5,
    reviewCount: 12,
    material: "Water-resistant polyester",
    dimensions: "30 x 45 x 15 cm",
    capacity: "25 liters",
    isFeatured: true,
  },
  {
    id: "2",
    name: "Designer Tote Bag",
    description:
      "Elegant tote bag with spacious interior. Perfect for work or casual outings.",
    price: 5600,
    category: "handbags",
    image: "https://placehold.co/600x600?text=Tote",
    stock: 5,
    rating: 4.8,
    reviewCount: 24,
    material: "Premium vegan leather",
    dimensions: "40 x 30 x 12 cm",
    isFeatured: false,
  },
  {
    id: "3",
    name: "Weekend Travel Bag",
    description:
      "Durable travel bag with ample storage for short trips. Includes a shoe compartment.",
    price: 7500,
    salePrice: 6750,
    category: "travel",
    image: "https://placehold.co/600x600?text=Travel+Bag",
    stock: 8,
    rating: 4.2,
    reviewCount: 18,
    material: "Canvas with leather trim",
    dimensions: "55 x 35 x 25 cm",
    capacity: "40 liters",
    isFeatured: true,
  },
  {
    id: "4",
    name: "Slim Bifold Wallet",
    description:
      "Sleek, minimalist wallet with RFID protection. Holds up to 8 cards plus cash.",
    price: 1600,
    category: "wallets",
    image: "https://placehold.co/600x600?text=Wallet",
    stock: 15,
    rating: 4.0,
    reviewCount: 35,
    material: "Genuine leather",
    dimensions: "11 x 9 x 1.5 cm",
    isFeatured: false,
  },
  {
    id: "5",
    name: "Crossbody Sling Bag",
    description:
      "Lightweight and compact sling bag for essentials. Water-resistant with anti-theft features.",
    price: 2800,
    category: "handbags",
    image: "https://placehold.co/600x600?text=Sling+Bag",
    stock: 7,
    rating: 4.6,
    reviewCount: 14,
    material: "Nylon",
    dimensions: "20 x 30 x 10 cm",
    capacity: "7 liters",
    isFeatured: false,
  },
  {
    id: "6",
    name: "Leather Messenger Bag",
    description:
      "Classic messenger bag with adjustable strap and multiple pockets for organization.",
    price: 4800,
    category: "backpacks",
    image: "https://placehold.co/600x600?text=Messenger",
    stock: 0, // Out of stock
    rating: 4.9,
    reviewCount: 42,
    material: "Full-grain leather",
    dimensions: "38 x 28 x 10 cm",
    capacity: "15 liters",
    isFeatured: true,
  },
];
